# coding: utf-8

"""
    WASAPhoto Backend

    Keep in touch with your friends by sharing photos of special moments, thanks to WASAPhoto! You can upload your photos directly from your PC, and they will be visible to everyone following you.

    The version of the OpenAPI document: 1.0.0
    Contact: deodati.2025953@studenti.uniroma1.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.account_management_api import router as AccountManagementApiRouter
from openapi_server.apis.feed_tools_api import router as FeedToolsApiRouter
from openapi_server.apis.followers_api import router as FollowersApiRouter
from openapi_server.apis.login_api import router as LoginApiRouter
from openapi_server.apis.post_tools_api import router as PostToolsApiRouter
from openapi_server.apis.users_api import router as UsersApiRouter

app = FastAPI(
    title="WASAPhoto Backend",
    description="Keep in touch with your friends by sharing photos of special moments, thanks to WASAPhoto! You can upload your photos directly from your PC, and they will be visible to everyone following you.",
    version="1.0.0",
)

app.include_router(AccountManagementApiRouter)
app.include_router(FeedToolsApiRouter)
app.include_router(FollowersApiRouter)
app.include_router(LoginApiRouter)
app.include_router(PostToolsApiRouter)
app.include_router(UsersApiRouter)
