"""initial schema

Revision ID: 246dba833063
Revises: 
Create Date: 2026-03-30 17:38:27.127875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246dba833063'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username'),
    schema='wasntaphoto'
    )
    op.create_index('ix_users_username_trgm', 'users', ['username'], unique=False, schema='wasntaphoto', postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    op.create_table('blocking',
    sa.Column('blocked_id', sa.BigInteger(), nullable=False),
    sa.Column('blocker_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('blocked_id != blocker_id', name='ck_no_self_block'),
    sa.ForeignKeyConstraint(['blocked_id'], ['wasntaphoto.users.user_id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['wasntaphoto.users.user_id'], ),
    sa.PrimaryKeyConstraint('blocked_id', 'blocker_id'),
    schema='wasntaphoto'
    )
    op.create_table('following',
    sa.Column('follower_id', sa.BigInteger(), nullable=False),
    sa.Column('following_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('follower_id != following_id', name='ck_no_self_follow'),
    sa.ForeignKeyConstraint(['follower_id'], ['wasntaphoto.users.user_id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['wasntaphoto.users.user_id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'following_id'),
    schema='wasntaphoto'
    )
    op.create_table('posts',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('caption', sa.String(length=2048), nullable=True),
    sa.Column('pub_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['wasntaphoto.users.user_id'], ),
    sa.PrimaryKeyConstraint('post_id'),
    schema='wasntaphoto'
    )
    op.create_table('user_sessions',
    sa.Column('session_id', sa.String(length=43), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('valid_until', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['wasntaphoto.users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    schema='wasntaphoto'
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.String(length=2048), nullable=False),
    sa.Column('pub_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['wasntaphoto.users.user_id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['wasntaphoto.posts.post_id'], ),
    sa.PrimaryKeyConstraint('comment_id'),
    schema='wasntaphoto'
    )
    op.create_table('post_like_relationship',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['wasntaphoto.posts.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wasntaphoto.users.user_id'], ),
    sa.PrimaryKeyConstraint('post_id', 'user_id'),
    schema='wasntaphoto'
    )
    op.create_table('comment_like_relationship',
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['wasntaphoto.comments.comment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['wasntaphoto.users.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id', 'user_id'),
    schema='wasntaphoto'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_like_relationship', schema='wasntaphoto')
    op.drop_table('post_like_relationship', schema='wasntaphoto')
    op.drop_table('comments', schema='wasntaphoto')
    op.drop_table('user_sessions', schema='wasntaphoto')
    op.drop_table('posts', schema='wasntaphoto')
    op.drop_table('following', schema='wasntaphoto')
    op.drop_table('blocking', schema='wasntaphoto')
    op.drop_index('ix_users_username_trgm', table_name='users', schema='wasntaphoto', postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    op.drop_table('users', schema='wasntaphoto')
    # ### end Alembic commands ###
